### ISSUE TITLE
Unable to generate 8 digit native Authy TOTP

### ISSUE THREAD

**Issue by justinmartin** [momaek/authy#13]
Clever.com implements Authy's TOTP directly.  The code generated in Authy is 8 digits, is it possible for the client to generate an 7 digit code for it?

**Comment by justinmartin** [comment]
I apologize, the client is generating a 7 digit code.  However, the Clever never accepts it?  Any suggestions how to troubleshoot this?

**Comment by momaek** [comment]
Can google or github accept it ?

**Comment by pyrmont** [comment]
I'm having the same issue with my Cloudflare token. Based on the following from the [README](https://github.com/alexzorin/authy/blob/0c25c0dd9ab1b54dafb47a801fc7277cfbfd8035/README.md) for Alex Zorin's Authy library, it looks like this is caused by the fact that there are two types of tokens:

> In Authy, there are two types of secrets:
> 
> - **Tokens**: You sign up to a website, the website generates a TOTP secret, and you scan it via a QR code (in any app, not necessarily Authy). You can export that secret to other TOTP apps and the code will match.
> - **Apps**: The website has exported their TOTP flow to Authy's proprietary service, which requires you to use the Authy app. For sites like Twitch, Authy assigns a unique TOTP secret for every device you use the Authy app on. Each device will produce different 7-digit codes, but they will all work. If you deregister any device from your Authy account, that device's TOTP secrets will be revoked and its 7-digit codes will no longer work.

When I try to enter the code that's generated by the Go binary, I get an error message from Cloudflare saying I need to use the token from the app on my phone.

**Comment by momaek** [comment]
> 

emmmm... I'll figure out a solution for this case.
